### ISSUE TITLE
Binder examples fail with TypeError: get_coordinates() argument after ** must be a mapping, not NoneType

### ISSUE THREAD

**Issue by rsignell-usgs** [oceanhackweek/ohw19-project-co_locators#21]
I tried both binder links, but both fail on
```
all_coords = erddap_query.get_coordinates(ui.df, **ui.kw)
```
with the error:
```
TypeError: get_coordinates() argument after ** must be a mapping, not NoneType
```

**Comment by mwengren** [comment]
@rsignell-usgs you need to select parameters in the controls that are output in cells 2 - 4, there aren't defaults assigned.

If you don't, the kw variable is None.  I got the same error if I don't specify a bbox, timeperiod, or standard_name in the selections.  We never got a full Panel-based UI working to make this more obvious, but we'd sure like to!

![colocators_ui_err](https://user-images.githubusercontent.com/1469921/96123652-23617a80-0ec1-11eb-9d14-05beba74e354.png)

**Comment by mwengren** [comment]
Also, run the colocate-dev notebook, it's a little more polished.  Plotting will most likely fail in the first one since it doesn't use DataShader.  

The initial search of 51 ERDDAPs is really slow right now.  Looks like some new servers got added to the Awesome ERDDAP list that are slow to respond.  We really need to parallelize/add timeouts to this step.

**Comment by mwengren** [comment]
@rsignell-usgs This works, you just need to hit the 'Search Servers' button after Cell 5 after selecting your filter criteria.  Otherwise, you will see this error message you noted. 

I just ran this notebook successfully via Binder:   [![binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/ioos/colocate/master?filepath=notebooks%2Fcolocate-dev.ipynb)

Give it a shot, it's not fast and has a lot of warts still, but does actually return data and shows the first 10 records at random plotted in HoloViz.  Going to close this issue out.
